In [14]:
#Create a NumPy array of numbers 1–20 and print only the even ones (boolean mask).
import numpy as np
arr=np.arange(1,21)
mask=arr%2==0
print(f"Even numbers between {arr[mask]}")
print("-"*33)
#Make a 3×3 array of random integers 1–100; print its mean, max, and the sum of each column.
arr=np.random.randint(1,100,size=(3,3))
mean=arr.mean()
max_num=arr.max()
print(f"Array :\n{arr}")
print(f"Mean : {mean}")
print(f"Max :{max_num}")
print(f"Sum : {arr.sum(axis=0)}")
print("-"*33)
#Given temps = np.array([30, 35, 28, 40, 33]), convert all to Fahrenheit in one line.
temps = np.array([30, 35, 28, 40, 33])
print(temps*9/5+32)

Even numbers between [ 2  4  6  8 10 12 14 16 18 20]
---------------------------------
Array :
[[25 24  3]
 [47 32 64]
 [26 36 75]]
Mean : 36.888888888888886
Max :75
Sum : [ 98  92 142]
---------------------------------
[ 86.   95.   82.4 104.   91.4]


In [ ]:
#Create a DataFrame of 5 products with Price and Quantity; add aTotal = Price × Quantity column.
import pandas as pd
data={
    "Products":["Dal","Rice","Milk","Oil","Soap"],
    "Quantity":[3,1,2,2,5],
    "Price":[120,1500,30,156,35]
}
df=pd.DataFrame(data)
print("Intial Dataset")
print(df)
print("-"*133)
df["TotalPrice"]=df["Price"]*df["Quantity"]
print("Adding Totalprice column Dataset")
print(df)
print("-"*133)
print("Dataset head")
print(df.head())
print("-"*133)
print("Dataset Shape")
print(df.shape)
print("-"*133)
print("Dataset info")
print(df.info())
print("-"*133)
print("Dataset Describe")
print(df.describe())
print("-"*133)
print("DataFrame to rows where Price > 100 and Quantity > 5.")
mask=(df["Price"]>100) & (df["Quantity"]>5)
print(df[mask])
print("Find the top 3 rows by a numeric column using nlargest.")
print(df.nlargest)

Intial Dataset
  Products  Quantity  Price
0      Dal         3    120
1     Rice         1   1500
2     Milk         2     30
3      Oil         2    156
4     Soap         5     35
-------------------------------------------------------------------------------------------------------------------------------------
Adding Totalprice column Dataset
  Products  Quantity  Price  TotalPrice
0      Dal         3    120         360
1     Rice         1   1500        1500
2     Milk         2     30          60
3      Oil         2    156         312
4     Soap         5     35         175
-------------------------------------------------------------------------------------------------------------------------------------
Dataset head
  Products  Quantity  Price  TotalPrice
0      Dal         3    120         360
1     Rice         1   1500        1500
2     Milk         2     30          60
3      Oil         2    156         312
4     Soap         5     35         175
-----------------------